### PR TITLE
Lesson 1 1

### PR DESCRIPTION
**Pull request by MilaKova**

### CODE REVIEW

**Review by GinaCastromonte — COMMENTED** [review]
Hey Mila! Your code is looking great.  However, I noticed a few areas where you can make improvements for better readability and maintainability.  The curly brackets around the <ul> 
element is unnecessary.  Also the return isn't needed on line 37. I would use the "key" attribute in the list.  When mapping through an array to render items in React, it's important to provide a unique "key " prop to each rendered element.  (https://react.dev/learn/rendering-lists#why-does-react-need-keys)

**Comment by MilaKova** [comment]
> Hey Mila! Your code is looking great. However, I noticed a few areas where you can make improvements for better readability and maintainability. The curly brackets around the
> 
> 
> element is unnecessary. Also the return isn't needed on line 37. I would use the "key" attribute in the list. When mapping through an array to render items in React, it's important to provide a unique "key " prop to each rendered element. (https://react.dev/learn/rendering-lists#why-does-react-need-keys)

Hi Gina! 
thank you so much for reviewing my work!
I have some questions, you said the return isn't needed, if I understand correctly, I should remove the return? (like below) 
function TodoList(){
      return(
        <ul style={{listStyleType: 'none',}}>
          {todoList.map((item)=>{
             <li key={item.id}>{item.title}</li>;
          })}
        </ul>      
      )
    }
but the code isn't working how

And one more question, how should I fix the code , if I already closed and merged pull request? I afraid to mess it up with next lessons.

**Comment by MilaKova** [comment]
Hi Gina!
thank you so much for reviewing my work!
I have some questions, you said the return isn't needed, if I understand correctly, I should remove the return? (like below)
   function TodoList(){
   return(
       <ul style={{listStyleType: 'none',}}>
       {todoList.map((item)=>{
            <lI key={item.id}>{item.title}</lI>

})}

)
}
but the code isn't working how
And one more question, how should I fix the code , if I already closed and merged pull request? I afraid to mess it up with next lessons.

**Comment by MilaKova** [comment]
Hi Gina!
thank you so much for reviewing my work!
I have some questions, you said the return isn't needed, if I understand correctly, I should remove the  return? (like below)
function App() {
  return (
    <div style={{ textAlign: 'center',}}>
      <header>          
        <h1>Todo list</h1> 
      </header>

        <ul style={{listStyleType: 'none',}}>

          {todoList.map((item)=> {
          <li key={item.ID}>{item.title}</li>;
          })}

        </ul>
      
      
    </div>
  );
}

but the code isn't working how
And one more question, how should I fix the code , if I already closed and merged pull request? I afraid to mess it up with next lessons.

**Comment by MilaKova** [comment]
Hi Gina! 
thank you so much for reviewing my work!
I have some questions, how can I edit code  if I already closed and merged pull request, I'm afraid to mess  up with next lessons. Should I make new branch? thank you

**Comment by MilaKova** [comment]
sorry for the copy/paste, I tried to make it nicer, but it keep loosing lines(

**Pull request merged**
